version: "3"
services:
  api:
    build:  .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "./:/go/src/app"
  psql:
    container_name: "psql"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dbuser
      POSTGRES_DB: database
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.11.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379